title: Fazed
subtitle: Example fazed website
description: >-
  This is an example website of the fazed theme for Jekyll
author: Caleb Froese
email: contact@calebfroese.com
theme: fazed
gems:
  - jekyll-bootstrap-sass
sass:
  sass_dir: _sass